#!/usr/bin/env python

SConsignFile(None)

env = SConscript("../../.deps/godot-cpp/SConstruct")

env.Append(CPPPATH=[
    "src",
    "../../.deps/quickhull",
])

objects = [
    env.SharedObject("bin/register_types", "src/register_types.cpp"),
    env.SharedObject("bin/native_convex_hull_util", "src/native_convex_hull_util.cpp"),
    env.SharedObject("bin/QuickHull", "../../.deps/quickhull/QuickHull.cpp"),
]

target = "bin/open_brush_hull{}{}".format(env["suffix"], env["SHLIBSUFFIX"])
library = env.SharedLibrary(target, source=objects)
Default(library)
